version: 1.0.{build}
image: Visual Studio 2019

# Установите Node.js
environment:
  nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Запустите сборку проекта
build_script:
  - npm run build
